### ISSUE TITLE
Cannot profile constructors

### ISSUE THREAD

**Issue by roncli** [gdborton/screeps-profiler#18]
I can see that constructors have been blacklisted from profiling... however, I have a few classes that I would like to profile the constructor for.  registerFN is not doing the trick, as it still gets blacklisted.  How would I go about registering these constructors for profiling?

**Comment by roncli** [comment]
FYI I work around this by, in the constructor, calling `this.init()`, and just making an `init` function, which is profiled just fine by the profiler.

**Comment by gdborton** [comment]
Labeled this as a won't fix, due to how class constructors need to be called (`new Creep()`). I'm not sure that it's safe to try to detect this and conditionally call the wrapped function with `new`.

For anyone reading this issue, the posted workaround is also the suggested work around.
