### ISSUE TITLE
Game.profiler.output() shows incorrect Avg and Ticks

### ISSUE THREAD

**Issue by roncli** [gdborton/screeps-profiler#8]
I did a Game.profiler.profile(20), and then later did a Game.profiler.output() a few times.  Basically, the tick counter on this output increases even though further profiling is not happening.  This only affects the final summary line.  Here is the summary line from two different Game.profiler.output() calls:

```
Avg: 9.13   Total: 246.43   Ticks: 27
```

```
Avg: 3.52   Total: 246.43   Ticks: 70
```

**Comment by gdborton** [comment]
This has been PR'd and accepted, will be in the next release of screeps-profiler.
